GestorFAEDCOH/Models/Base de datos/ACTIVIDAD.cs
namespace GestorFAEDCOH.Models.Base_de_datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;

    [Table("ACTIVIDAD")]
    public partial class ACTIVIDAD
    {
        [Key]
        public int ID_ACTIVIDAD { get; set; }

        [Required]
        [StringLength(50)]
        public string NOMBRE { get; set; }

        [Required]
        [StringLength(60)]
        public string DESCRIPCION { get; set; }

        public int ID_AUTOR { get; set; }

        public int ID_TIPO_ACTIVIDAD { get; set; }

        public bool? ESTADO { get; set; }

        public int ID_ENCARGADO { get; set; }

        [Column(TypeName = "date")]
        public DateTime FECHA_INICIO { get; set; }

        [Column(TypeName = "date")]
        public DateTime FECHA_FIN { get; set; }

        public virtual USUARIO USUARIO { get; set; }

        public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }

        public virtual USUARIO USUARIO1 { get; set; }

        public List<ACTIVIDAD> ListarTodo()
        {
            var ACTIVIDAD = new List<ACTIVIDAD>();

            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    ACTIVIDAD = db.ACTIVIDAD.Include("TIPO_ACTIVIDAD")
                        .Include("USUARIO")
                        .ToList();
                }
            }
            catch (Exception e)
            {
                throw;
            }

            return ACTIVIDAD;
        }

        public void Guardar()
        {
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_ACTIVIDAD > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else
                    {
                        db.Entry(this).State = EntityState.Added;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                throw;
            }
        }

        public ACTIVIDAD ObtenerACTIVIDAD(int id)
        {
            var ACTIVIDAD = new ACTIVIDAD();

            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    ACTIVIDAD = db.ACTIVIDAD
                        .Where(x => x.ID_ACTIVIDAD == id)
                        .SingleOrDefault();
                }
            }
            catch (Exception)
            {
                throw;
            }

            return ACTIVIDAD;
        }

        public void Eliminar()
        {
            var ACTIVIDAD = ObtenerACTIVIDAD(ID_ACTIVIDAD);
            this.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD;
            this.NOMBRE = ACTIVIDAD.NOMBRE;
            this.DESCRIPCION = ACTIVIDAD.DESCRIPCION;
            this.ID_AUTOR = ACTIVIDAD.ID_AUTOR;
            this.ID_TIPO_ACTIVIDAD = ACTIVIDAD.ID_TIPO_ACTIVIDAD;
            this.ESTADO = ACTIVIDAD.ESTADO;
            this.ID_ENCARGADO = ACTIVIDAD.ID_ENCARGADO;
            this.FECHA_INICIO = ACTIVIDAD.FECHA_INICIO;
            this.FECHA_FIN = ACTIVIDAD.FECHA_FIN;
            this.ESTADO = false;
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_TIPO_ACTIVIDAD > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                throw;
            }
        }

        public void Habilitar()
        {
            var ACTIVIDAD = ObtenerACTIVIDAD(ID_ACTIVIDAD);
            this.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD;
            this.NOMBRE = ACTIVIDAD.NOMBRE;
            this.DESCRIPCION = ACTIVIDAD.DESCRIPCION;
            this.ID_AUTOR = ACTIVIDAD.ID_AUTOR;
            this.ID_TIPO_ACTIVIDAD = ACTIVIDAD.ID_TIPO_ACTIVIDAD;
            this.ESTADO = ACTIVIDAD.ESTADO;
            this.ID_ENCARGADO = ACTIVIDAD.ID_ENCARGADO;
            this.FECHA_INICIO = ACTIVIDAD.FECHA_INICIO;
            this.FECHA_FIN = ACTIVIDAD.FECHA_FIN;
            this.ESTADO = true;
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_TIPO_ACTIVIDAD > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                throw;
            }
        }

        public void Revision()
        {
            var ACTIVIDAD = ObtenerACTIVIDAD(ID_ACTIVIDAD);
            this.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD;
            this.NOMBRE = ACTIVIDAD.NOMBRE;
            this.DESCRIPCION = ACTIVIDAD.DESCRIPCION;
            this.ID_AUTOR = ACTIVIDAD.ID_AUTOR;
            this.ID_TIPO_ACTIVIDAD = ACTIVIDAD.ID_TIPO_ACTIVIDAD;
            this.ESTADO = ACTIVIDAD.ESTADO;
            this.ID_ENCARGADO = ACTIVIDAD.ID_ENCARGADO;
            this.FECHA_INICIO = ACTIVIDAD.FECHA_INICIO;
            this.FECHA_FIN = ACTIVIDAD.FECHA_FIN;
            this.ESTADO = null;
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_TIPO_ACTIVIDAD > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                throw;
            }
        }
    }
}

GestorFAEDCOH/Controllers/ActividadController.cs
using GestorFAEDCOH.Models.Base_de_datos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static GestorFAEDCOH.Filtros.AdminFilters;

namespace GestorFAEDCOH.Controllers
{
    [Autenticado]
    public class ActividadController : Controller
    {
        USUARIO usuario = new USUARIO();
        ACTIVIDAD actividad = new ACTIVIDAD();
        TIPO_ACTIVIDAD tipo_actividad = new TIPO_ACTIVIDAD();

        // GET: Actividad
        public ActionResult Index()
        {
            ViewBag.Usuario = usuario.ListarTodo();
            ViewBag.Tipo_Actividad = tipo_actividad.ListarTodo();
            return View(actividad.ListarTodo());
        }

        public ActionResult Guardar(ACTIVIDAD actividad, string daterange)
        {
            if (!actividad.DESCRIPCION.Equals("") && !daterange.Equals(""))
            {
                //split de la fecha
                string[] fechas = daterange.Split('-');
                actividad.FECHA_INICIO = Convert.ToDateTime(fechas[0]);
                actividad.FECHA_FIN = Convert.ToDateTime(fechas[1]);

                actividad.Guardar();
                return Redirect("~/Actividad/Index");
            }
            else
            {
                return View("~/Actividad/Index");
            }
        }

        public ActionResult EditAct(int id = 0)
        {
            ViewBag.Usuario = usuario.ListarTodo();
            ViewBag.Tipo_Actividad = tipo_actividad.ListarTodo();
            return View(id == 0 ? new ACTIVIDAD() : actividad.ObtenerACTIVIDAD(id));
        }

        public ActionResult Eliminar(int id)
        {
            actividad.ID_ACTIVIDAD = id;
            actividad.Eliminar();
            return Redirect("~/Actividad/Index");
        }

        public ActionResult Habilitar(int id)
        {
            actividad.ID_ACTIVIDAD = id;
            actividad.Habilitar();
            return Redirect("~/Actividad/Index");
        }

        public ActionResult Revision(int id)
        {
            actividad.ID_ACTIVIDAD = id;
            actividad.Revision();
            return Redirect("~/Actividad/Index");
        }
    }
}

GestorFAEDCOH/Views/Actividad/EditAct.cshtml
@model GestorFAEDCOH.Models.Base_de_datos.ACTIVIDAD
@{
    ViewBag.Title = "EditPro";
    Layout = "~/Views/Shared/Layout.cshtml";
    List<GestorFAEDCOH.Models.Base_de_datos.TIPO_ACTIVIDAD> tipo_actividad = ViewBag.Tipo_Actividad;
    List<GestorFAEDCOH.Models.Base_de_datos.USUARIO> usuario = ViewBag.Usuario;
}

<div class="row" style="padding: 10px;">

    @using (Html.BeginForm("Guardar", "Actividad", FormMethod.Post, new { id = "frm-actividad" }))
    {
        string p = "";
        @Html.HiddenFor(x => Model.ID_ACTIVIDAD)
        @Html.HiddenFor(x => Model.ESTADO)

        if (Model.ESTADO == true)
        {
            p = "Activo";
        }
        else if (Model.ESTADO == false)
        {
            p = "Cancelado";
        }
        else
        {
            p = "En Revision";
        }


        <div class="form">

            <div class="row card-box">
                <h4 class="header-title"><i class="fa fa-pencil"></i> Editar @Model.NOMBRE</h4>
            </div>

            <div class="row card-box">
                <h4 class="header-title m-t-0 m-b-30">Datos de generales</h4>

                <div class="col-md-5">
                    <div class="form-group">
                        @Html.Label("Nombre", new { @class = "control-label" })
                        @Html.TextBoxFor(x => Model.NOMBRE, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.NOMBRE, null, new { @class = "label label-danger" })
                    </div>
                </div>

                <div class="col-md-7">
                    <div class="form-group">
                        @Html.Label("Descripcion", new { @class = "control-label" })
                        @Html.TextBoxFor(x => Model.DESCRIPCION, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.DESCRIPCION, null, new { @class = "label label-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Autor", new { @class = "control-label" })
                        <select name="ID_AUTOR" id="ID_AUTOR" class="form-control">
                            @foreach (var user in usuario)
                            {
                                if (user.ID_TIPOUSUARIO == 7)
                                {
                                    if (user.ID_USUARIO == Model.ID_AUTOR)
                                    {
                                        <option selected value="@user.ID_USUARIO">@user.NOMBRE</option>
                                    }
                                    else
                                    {
                                        <option value="@user.ID_USUARIO">@user.NOMBRE</option>
                                    }
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Encargado", new { @class = "control-label" })
                        <select name="ID_ENCARGADO" id="ID_ENCARGADO" class="form-control">
                            @foreach (var user in usuario)
                            {
                                if (user.ID_TIPOUSUARIO != 7)
                                {
                                    if (user.ID_USUARIO == Model.ID_ENCARGADO)
                                    {
                                        <option selected value="@user.ID_USUARIO">@user.NOMBRE</option>
                                    }
                                    else
                                    {
                                        <option value="@user.ID_USUARIO">@user.NOMBRE</option>
                                    }
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="row card-box">
                <h4 class="header-title m-t-0 m-b-30">Caracteristicas</h4>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Fecha de Inicio y Fin", new { @class = "control-label" })
                        <input class="form-control input-daterange-timepicker" type="text" name="daterange" value="@Model.FECHA_INICIO - @Model.FECHA_FIN" />
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.Label("Tipo de actividad", new { @class = "control-label" })
                        <select name="ID_TIPO_ACTIVIDAD" id="ID_TIPO_ACTIVIDAD" class="form-control">

                            @foreach (var metodo in tipo_actividad)
                            {
                                if (Model.ID_TIPO_ACTIVIDAD != metodo.ID_TIPO_ACTIVIDAD)
                                {
                                    <option value="@metodo.ID_TIPO_ACTIVIDAD">@metodo.DESCRIPCION</option>
                                }
                                else
                                {
                                    <option selected value="@metodo.ID_TIPO_ACTIVIDAD">@metodo.DESCRIPCION</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("ESTADO")
                        <input type="text" class="form-control" value="@p" readonly>
                    </div>
                </div>
            </div>

        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" onclick="goBack()">Cerrar</button>
            <button type="submit" class="btn btn-custom waves-effect waves-light">Guardar Cambios</button>
        </div>
    }

</div>


<!-- jQuery  -->
<script src="~/Source/js/jquery.min.js"></script>

<!-- Plugins Js para los calendarios -->
<script src="~/Source/plugins/switchery/switchery.min.js"></script>
<script src="~/Source/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
<script type="text/javascript" src="~/Source/plugins/multiselect/js/jquery.multi-select.js"></script>
<script type="text/javascript" src="~/Source/plugins/jquery-quicksearch/jquery.quicksearch.js"></script>
<script src="~/Source/plugins/select2/dist/js/select2.min.js" type="text/javascript"></script>
<script src="~/Source/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js" type="text/javascript"></script>
<script src="~/Source/plugins/bootstrap-inputmask/bootstrap-inputmask.min.js" type="text/javascript"></script>
<script src="~/Source/plugins/moment/moment.js"></script>
<script src="~/Source/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="~/Source/plugins/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<script src="~/Source/DatePicker/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
<script src="~/Source/DatePicker/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="~/Source/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>

<script>

    //Date range picker

    jQuery('#date-range').datepicker({
        toggleActive: true
    });

    $('.input-daterange-datepicker').daterangepicker({
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-default',
        cancelClass: 'btn-primary'
    });
    $('.input-daterange-timepicker').daterangepicker({
        timePicker: false,
        format: 'DD/MM/YYYY hh:mm:ss',
        timePickerIncrement: 30,
        timePicker12Hour: true,
        timePickerSeconds: false,
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-default',
        cancelClass: 'btn-primary'
    });
</script>