GestorFAEDCOH/Models/Base de datos/ETAPA.cs
namespace GestorFAEDCOH.Models.Base_de_datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;

    [Table("ETAPA")]
    public partial class ETAPA
    {
        [Key]
        public int ID_ETAPA { get; set; }

        [Required]
        [StringLength(40)]
        public string NOMBRE { get; set; }

        public int ID_TIPO_ACTIVIDAD { get; set; }

        public bool? ESTADO { get; set; }

        public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }

        public List<ETAPA> ListarTodo()
        {
            var etapa = new List<ETAPA>();

            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    etapa = db.ETAPA.Include("TIPO_ACTIVIDAD").ToList();
                }
            }

            catch (Exception e)

            {
                throw;
            }

            return etapa;
        }

        public void Guardar()
        {
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_ETAPA > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else
                    {
                        db.Entry(this).State = EntityState.Added;
                    }
                    db.SaveChanges();
                }
            }

            catch (Exception e)

            {
                throw;
            }
        }

        public ETAPA ObtenerEtapa(int id)
        {
            var etapa = new ETAPA();

            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    etapa = db.ETAPA
                        .Where(x => x.ID_ETAPA == id)
                        .SingleOrDefault();
                }
            }
            catch (Exception)
            {
                throw;
            }

            return etapa;
        }

        public void Eliminar()
        {
            var etapa = ObtenerEtapa(ID_ETAPA);
            this.ID_ETAPA = etapa.ID_ETAPA;
            this.NOMBRE = etapa.NOMBRE;
            this.ID_TIPO_ACTIVIDAD = etapa.ID_TIPO_ACTIVIDAD;
            this.ESTADO = false;
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_TIPO_ACTIVIDAD > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                throw;
            }
        }

        public void Habilitar()
        {
            var etapa = ObtenerEtapa(ID_ETAPA);
            this.ID_ETAPA = etapa.ID_ETAPA;
            this.NOMBRE = etapa.NOMBRE;
            this.ID_TIPO_ACTIVIDAD = etapa.ID_TIPO_ACTIVIDAD;
            this.ESTADO = true;
            try
            {
                using (var db = new bd_FAEDCOH())
                {
                    if (this.ID_TIPO_ACTIVIDAD > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
                throw;
            }
        }
    }
}

GestorFAEDCOH/Controllers/EtapaController.cs
using GestorFAEDCOH.Models.Base_de_datos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static GestorFAEDCOH.Filtros.AdminFilters;

namespace GestorFAEDCOH.Controllers
{
    [Autenticado]
    public class EtapaController : Controller
    {
        ETAPA etapa = new ETAPA();
        TIPO_ACTIVIDAD tipo_actividad = new TIPO_ACTIVIDAD();

        // GET: Etapa
        public ActionResult Index()
        {
            ViewBag.Tipo_Actividad = tipo_actividad.ListarTodo();
            return View(etapa.ListarTodo());
        }

        public ActionResult Guardar(ETAPA etapa)
        {
            if (ModelState.IsValid)
            {
                etapa.Guardar();
                return Redirect("~/Etapa/Index");
            }
            else
            {
                return View("~/Etapa/Index");
            }
        }

        public ActionResult EditEta(int id = 0)
        {
            ViewBag.Tipo_Actividad = tipo_actividad.ListarTodo();
            return View(id == 0 ? new ETAPA() : etapa.ObtenerEtapa(id));
        }

        public ActionResult Eliminar(int id)
        {
            etapa.ID_ETAPA = id;
            etapa.Eliminar();
            return Redirect("~/Etapa/Index");
        }

        public ActionResult Habilitar(int id)
        {
            etapa.ID_ETAPA = id;
            etapa.Habilitar();
            return Redirect("~/Etapa/Index");
        }
    }
}

GestorFAEDCOH/Views/Etapa/EditEta.cshtml
@model GestorFAEDCOH.Models.Base_de_datos.ETAPA
@{
    ViewBag.Title = "Editar Etapa";
    Layout = "~/Views/Shared/Layout.cshtml";
    List<GestorFAEDCOH.Models.Base_de_datos.TIPO_ACTIVIDAD> tipo_actividad = ViewBag.Tipo_Actividad;
}

<div class="row" style="padding: 10px;">

    @using (Html.BeginForm("Guardar", "Etapa", FormMethod.Post, new { id = "frm-etapa" }))
    {
        string p = "";
        @Html.HiddenFor(x => Model.ID_ETAPA)
        @Html.HiddenFor(x => Model.ESTADO)

        if (Model.ESTADO == true)
        {
            p = "Activo";
        }
        else
        {
            p = "Inactivo";
        }


        <div class="form">

            <div class="row card-box">
                <h4 class="header-title"><i class="fa fa-pencil"></i> Editar Etapa de @Model.NOMBRE</h4>
            </div>

            <div class="row card-box">
                <h4 class="header-title m-t-0 m-b-30">Datos de generales</h4>
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.Label("Nombre", new { @class = "control-label" })
                        @Html.TextBoxFor(x => Model.NOMBRE, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.NOMBRE, null, new { @class = "label label-danger" })
                    </div>
                </div>
            </div>

            <div class="row card-box">
                <h4 class="header-title m-t-0 m-b-30">Otros datos</h4>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Tipo de actividad", new { @class = "control-label" })
                        <select name="ID_TIPO_ACTIVIDAD" id="ID_TIPO_ACTIVIDAD" class="form-control">

                            @foreach (var metodo in tipo_actividad)
                            {
                                if (Model.ID_TIPO_ACTIVIDAD != metodo.ID_TIPO_ACTIVIDAD)
                                {
                                    <option value="@metodo.ID_TIPO_ACTIVIDAD">Tipo_Actividad @metodo.DESCRIPCION</option>
                                }
                                else
                                {
                                    <option selected value="@metodo.ID_TIPO_ACTIVIDAD">Etapa @metodo.DESCRIPCION</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("ESTADO")
                        <input type="text" class="form-control" value="@p" readonly>
                    </div>
                </div>
            </div>

        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal" onclick="goBack()">Cerrar</button>
            <button type="submit" class="btn btn-custom waves-effect waves-light">Guardar Cambios</button>
        </div>
    }

</div>

GestorFAEDCOH/Views/Etapa/Index.cshtml
@model List<GestorFAEDCOH.Models.Base_de_datos.ETAPA>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    List<GestorFAEDCOH.Models.Base_de_datos.TIPO_ACTIVIDAD> tipo_actividad = ViewBag.Tipo_Actividad;
    int i = 0;
}

<div class="row">
    <div class="col-sm-6">
        <div class="m-b-30">
            <a data-toggle="modal" data-target="#modal-Agregar-Etapa" class="btn btn-rounded btn-custom waves-effect waves-light"><i class="fa fa-plus"></i> Agregar nueva etapa</a>
        </div>
    </div>
</div>

<!--Row de listado de los datos-->
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">

            <h2 class="header-title m-t-0 m-b-30"><i class="fa fa-book"></i>Lista de etapas</h2>

            <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead class="bg-custom">
                    <tr>
                        <th class="text-white">ID</th>
                        <th class="text-white">Nombre</th>
                        <th class="text-white">Tipo de actividad</th>
                        <th class="text-white">Estado</th>
                        <th class="text-white">Acciones</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var etapa in Model)
                    {
                        if (etapa.ESTADO == true)
                        {
                            <tr>
                                <td style="vertical-align: middle;">@etapa.ID_ETAPA</td>
                                <td style="vertical-align: middle;">Etapa de @etapa.NOMBRE</td>
                                <td style="vertical-align: middle;">@etapa.TIPO_ACTIVIDAD.DESCRIPCION</td>

                                @if (etapa.ESTADO == true)
                                {
                                    <td style="vertical-align: middle;">Activo</td>
                                }
                                else
                                {
                                    <td style="vertical-align: middle;">Inactivo</td>
                                }


                                <td style="vertical-align: middle;" align="center" class="actions">

                                    <div class="input-group-btn btn-rounded">
                                        <button type="button" class="btn btn-rounded waves-effect waves-light btn-success btn-trans" style="overflow: hidden; position: relative;">Acciones</button>
                                        <button type="button" class="btn btn-rounded waves-effect waves-light btn-success btn-trans dropdown-toggle" data-toggle="dropdown" style="overflow: hidden; position: relative;"><span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a id="editar" href="~/Etapa/EditEta/@etapa.ID_ETAPA"><i class="fa fa-pencil text-warning"></i> Editar</a></li>
                                            <li><a href="~/Etapa/Eliminar/@etapa.ID_ETAPA" onclick="return confirm('¿Esta seguro de eliminarla?')"><i class="fa fa-trash-o text-danger"></i> Eliminar</a></li>
                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        }


                        else if (etapa.ESTADO == false)
                        {
                            <tr>
                                <td style="vertical-align: middle;">@etapa.ID_ETAPA</td>
                                <td style="vertical-align: middle;" class="text-danger"><i class="ti ti-alert"></i>Etapa de @etapa.NOMBRE</td>
                                <
                                <td style="vertical-align: middle;">@etapa.TIPO_ACTIVIDAD.DESCRIPCION</td>

                                @if (etapa.ESTADO == true)
                                {
                                    <td style="vertical-align: middle;">Activo</td>
                                }
                                else
                                {
                                    <td style="vertical-align: middle;">Inactivo</td>
                                }


                                <td style="vertical-align: middle;" align="center" class="actions">

                                    <div class="input-group-btn btn-rounded">
                                        <button type="button" class="btn btn-rounded waves-effect waves-light btn-success btn-trans" style="overflow: hidden; position: relative;">Acciones</button>
                                        <button type="button" class="btn btn-rounded waves-effect waves-light btn-success btn-trans dropdown-toggle" data-toggle="dropdown" style="overflow: hidden; position: relative;"><span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a id="editar" href="~/Etapa/EditEta/@etapa.ID_ETAPA"><i class="fa fa-pencil text-warning"></i> Editar</a></li>
                                            <li><a href="~/Etapa/Habilitar/@etapa.ID_ETAPA" onclick="return confirm('¿Esta seguro de habilitarla?')"><i class="fa fa-check text-success"></i> Habilitar</a></li>
                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal para agregar la etapa -->
<div id="modal-Agregar-Etapa" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content" style="border-radius: 15px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Datos de la etapa</h4>
            </div>

            @using (Html.BeginForm("Guardar", "Etapa", FormMethod.Post, new { id = "frm-etapa" }))
            {

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.Label("Nombre", new { @class = "control-label" })
                                <input type="text" name="NOMBRE" id="NOMBRE" class="form-control" placeholder="Ingrese el nombre de la etapa" required>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("Tipo de actividad", new { @class = "control-label" })
                                <select name="ID_TIPO_ACTIVIDAD" id="ID_TIPO_ACTIVIDAD" class="form-control">
                                    @foreach (var metodo in tipo_actividad)
                                    {
                                        if (i == 0)
                                        {
                                            <option selected value="@metodo.ID_TIPO_ACTIVIDAD">@metodo.DESCRIPCION</option>
                                            i++;
                                        }
                                        else
                                        {
                                            <option value="@metodo.ID_TIPO_ACTIVIDAD">@metodo.DESCRIPCION</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label("ESTADO")
                                <select name="ESTADO" id="ESTADO" class="form-control">
                                    <option selected value="true">Activo</option>
                                    <option value="false">Inactivo</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-rounded btn-default waves-effect" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-rounded btn-custom waves-effect waves-light">Agregar</button>
                </div>
            }

        </div>
    </div>
</div>